module.exports = {
    video1_1: 'http://видео.атм-мотивация.рф/?utm_source=vk&utm_medium=message&utm_campaign=funnel_1&utm_content=video1_1&utm_term=video+lesson+1',
    video1_2: 'http://видео.атм-мотивация.рф/?utm_source=vk&utm_medium=message&utm_campaign=funnel_1&utm_content=video1_2&utm_term=video+lesson+2',
    video1_3: 'http://видео.атм-мотивация.рф/?utm_source=vk&utm_medium=message&utm_campaign=funnel_1&utm_content=video1_3&utm_term=video+lesson+3',
    video5_about: 'http://атм-гденьги.рф/?utm_source=vk&utm_medium=message&utm_campaign=funnel_1&utm_content=video5_about&utm_term=about+gdengi+1',
    video4_1: 'http://видео.атм-статистики.рф/?utm_source=vk&utm_medium=message&utm_campaign=funnel_1&utm_content=video4_1&utm_term=video+lesson+1',
    video4_2: 'http://видео.атм-статистики.рф/?utm_source=vk&utm_medium=message&utm_campaign=funnel_1&utm_content=video4_2&utm_term=video+lesson+2',
    video4_3: 'http://видео.атм-статистики.рф/?utm_source=vk&utm_medium=message&utm_campaign=funnel_1&utm_content=video4_3&utm_term=video+lesson+3',
    video5: 'http://видео.атм-гденьги.рф/?utm_source=vk&utm_medium=message&utm_campaign=funnel_1&utm_content=video5&utm_term=gdengi_watch',
    video5_1_about: 'http://атм-гденьги.рф/?utm_source=vk&utm_medium=message&utm_campaign=funnel_1&utm_content=video5_1_about&utm_term=about+gdengi+2',
    video6_about: 'http://атм-интенсив.рф/?utm_source=vk&utm_medium=message&utm_campaign=funnel_1&utm_content=video6_about&utm_term=about_intensiv+1',
    video3_1: 'http://видео.атм-фонды.рф/?utm_source=vk&utm_medium=message&utm_campaign=funnel_1&utm_content=video3_1&utm_term=video+lesson+1',
    video6: 'http://видео.атм-гденьги.рф/?utm_source=vk&utm_medium=message&utm_campaign=funnel_1&utm_content=video6&utm_term=intensiv_watch',
    video3_2: 'http://видео.атм-фонды.рф/?utm_source=vk&utm_medium=message&utm_campaign=funnel_1&utm_content=video3_2&utm_term=video+lesson+2',
    video6_1_about: 'http://атм-интенсив.рф/?utm_source=vk&utm_medium=message&utm_campaign=funnel_1&utm_content=video6_1_about&utm_term=about_intensiv+2',
    video2_1: 'http://видео.атм-фонды.рф/?utm_source=vk&utm_medium=message&utm_campaign=funnel_1&utm_content=video2_1&utm_term=video+lesson+1',
    video6_2_about: 'http://атм-интенсив.рф/?utm_source=vk&utm_medium=message&utm_campaign=funnel_1&utm_content=video6_2_about&utm_term=about_intensiv+3',
    video7_about: 'http://финансовое-планирование.рф/?utm_source=vk&utm_medium=message&utm_campaign=funnel_1&utm_content=video7_about&utm_term=about_fp',


    video5_pay(id){return `http://оплата.атм-гденьги.рф/checkout/162?p=0a2352e8-2758-e811-a99e-dfcd291211f5&attr=a8134ba7-d794-e811-a9a1-cd0220c5658a:${id}`},
    video5_1_pay(id){return `http://оплата.атм-гденьги.рф/checkout/162?p=0a2352e8-2758-e811-a99e-dfcd291211f5&attr=a8134ba7-d794-e811-a9a1-cd0220c5658a:${id}`},
    video6_pay(id){ `http://оплата.атм-интенсив.рф/checkout/246?p=52a8ba0b-d894-e811-a9a1-cd0220c5658a&attr=a8134ba7-d794-e811-a9a1-cd0220c5658a:${id}`},
    video6_1_pay(id){return `http://оплата.атм-интенсив.рф/checkout/246?p=52a8ba0b-d894-e811-a9a1-cd0220c5658a&attr=a8134ba7-d794-e811-a9a1-cd0220c5658a:${id}`},
    video6_2_pay(id){return `http://оплата.атм-интенсив.рф/checkout/246?p=52a8ba0b-d894-e811-a9a1-cd0220c5658a&attr=a8134ba7-d794-e811-a9a1-cd0220c5658a:${id}`},

    // video3npPay1: 'атм-мотивация.рф',
    // video3npPay2_next: 'атм-мотивация.рф',
    // video3npPay2_about: 'атм-мотивация.рф',
    // video3npPay3: 'атм-мотивация.рф',
    // video3npPay4: 'атм-мотивация.рф',
    // video3npPay5: 'атм-мотивация.рф',
    //
    // video4: 'атм-мотивация.рф',
    // video4_1_pay: 'атм-мотивация.рф',
    // video4_1_more: 'атм-мотивация.рф',
    // video4_2: 'атм-мотивация.рф',
    // video4_3: 'атм-мотивация.рф',
    // video4_4: 'атм-мотивация.рф',
    // video4_5: 'атм-мотивация.рф',
    // video4_6: 'атм-мотивация.рф',
    //
    // video5: 'атм-мотивация.рф',
    // video5_about: 'атм-мотивация.рф',
}